name: Deploy to VPS
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Build and deploy ZenTodo
              run: |
                  docker build -t zentodo .
                  docker stop zentodo || true
                  docker rm zentodo || true
                  docker run -d --name zentodo --network app_network -p 3001:3001 zentodo
              shell: cmd
