name: Deploy to VPS

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Convert repository name to lowercase
              id: repo-name
              run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.REPO_NAME }}:latest
                  build-args: |
                      MONGODB_URI=${{ secrets.MONGODB_URI }}
                      NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
                      NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
                      EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
                      EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
                      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
                      CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
                      NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
                      NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
                      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}
                      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Convert repository name to lowercase
              id: repo-name
              run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      # Pull the latest image
                      docker pull ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.REPO_NAME }}:latest

                      # Stop and remove the existing container (if it exists)
                      docker stop zentodo || true
                      docker rm zentodo || true

                      # Run the new container
                      docker run -d \
                        --name zentodo \
                        --network app_network \
                        -p 3001:3001 \
                        -e PORT=3001 \
                        -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
                        -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
                        -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
                        -e EDGE_STORE_ACCESS_KEY="${{ secrets.EDGE_STORE_ACCESS_KEY }}" \
                        -e EDGE_STORE_SECRET_KEY="${{ secrets.EDGE_STORE_SECRET_KEY }}" \
                        -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" \
                        -e CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
                        -e NEXT_PUBLIC_CLERK_SIGN_IN_URL="${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}" \
                        -e NEXT_PUBLIC_CLERK_SIGN_UP_URL="${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}" \
                        -e NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL="${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}" \
                        -e NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL="${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}" \
                        ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.REPO_NAME }}:latest
