name: Deploy to VPS

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner | lower }}/zentodo

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      docker stop zentodo || true
                      docker rm zentodo || true
                      docker run -d --name zentodo --network app_network -p 3001:3001 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
